#MANAGER MACHINE
FROM ubuntu:20.04

RUN mkdir app
WORKDIR /app

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get clean

#tail is a dummy process so container doesn't exit once the process is done
CMD tail -f /dev/null 