FROM python:3.12-slim


WORKDIR /app


COPY requirements.txt .


RUN python -m venv venv && venv/bin/pip install --no-cache-dir -r requirements.txt


COPY blockchain/ ./blockchain
COPY comms/ ./comms
COPY scenarios/one_on_one/main.py .
COPY utils/ ./utils



CMD ["venv/bin/python", "main.py"]